---
- name: Listen for newly created Namespace
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
        host: "https://api.cluster-b7knv.b7knv.sandbox2957.opentlc.com:6443"
        api_key: ""
        validate_certs: no
  rules:
    - name: Set Resource Quotas to a Namespace
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: set-resource-quota-on-namespace
          organization: Default
