---
- name: Listen for newly created Namespace
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
        host: "https://api.cluster-khbff.khbff.sandbox3061.opentlc.com:6443"
        api_key: "eyJhbGciOiJSUzI1NiIsImtpZCI6Il94UnBtbXB0SzdwTzBiaWlhaHk3RmZXOW1zTDBiT1dTaVVZSEdmTUJTam8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhYXAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGVmYXVsdC10b2tlbi1wOWh2YyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiODBhMzdlZTMtMzhiMi00NjBjLTg4ZGQtZjM3Y2YwNDBmMjhjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFhcDpkZWZhdWx0In0.a_SVQ20AjEY-FTfaq6n29rl2ZT1VZ2uCxmdcHjxHpJopzsyjng99rK_omi2rlHc0T62mNiXYA4HDwIkj_VokKXEcAG3sTzXA4WTE1gOPDSzSqStakk5mu1_ONSkgCZlOL74CQ6OfSi_Pfcl8GraY4R3dMq2BZU8gPoET7U-202WusoHl88uEw3MlotwGik8X98mZU5QaIsXiU57ra2gj5YVfwsIU13-aWaXjuCSQqTBNv_Z40YkmwqiBl4X9Uhlz8E9SQ-EMu1w-mRerQzfYPqeya4XtRekV3dKlokzUh7o_SY1Nus2Yf7WIFaUmfv1y-4MdpasGv27NIaSZDxOoE3lrxcVl1ONvZ07CRDTeRTFxD4ySeeN5xo3KMHvbsAYNBzKZIMe5ZOkhYF6Mt7nxouEDIFCg49EbWHTbLr_AFuVDRrZcldh5Sck9K7D8hJ2PAsY65KVZ5qUSdq8BcwAtRhhWMLX_uGWV07M1ul4vrdY7jaK25NZ-cj7HDq3IzYAOr6G7MrAQXJFswZtpT1IIa6be-ACE7tiNJ6rmc_nxSC8FmBS-EXo-MsA6MOwxtUAQi5C6_4OwkjYCEjN7SOqA0vL4pLPMJmhedDGD-ZjudzJwP8t_3sF7KfHkn-jYUpkEca-nOAjHm2BQwTDqAFNdV4vUT5l9yNXfHI3wgQUY8ng"
        validate_certs: no
  rules:
    - name: Set Resource Quotas to a Namespace
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: set-resource-quota-on-namespace
          organization: Default
